// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	AddCarOperation        OperationName = "AddCar"
	DeleteCarByIdOperation OperationName = "DeleteCarById"
	GetCarByIdOperation    OperationName = "GetCarById"
	ListCarsOperation      OperationName = "ListCars"
	UpdateCarByIdOperation OperationName = "UpdateCarById"
)
