// Code generated by ogen, DO NOT EDIT.
package oas

type DeleteCarByIdRes interface {
	deleteCarByIdRes()
}

type GetCarByIdRes interface {
	getCarByIdRes()
}

type UpdateCarByIdRes interface {
	updateCarByIdRes()
}
