// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddCar implements addCar operation.
//
// Add a new car to the storage.
//
// POST /cars
func (UnimplementedHandler) AddCar(ctx context.Context, req *NewCar) (r *Car, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteCarById implements deleteCarById operation.
//
// Remove a car from storage using its ID.
//
// DELETE /cars/{id}
func (UnimplementedHandler) DeleteCarById(ctx context.Context, params DeleteCarByIdParams) (r DeleteCarByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCarById implements getCarById operation.
//
// Get a car using its ID.
//
// GET /cars/{id}
func (UnimplementedHandler) GetCarById(ctx context.Context, params GetCarByIdParams) (r GetCarByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListCars implements listCars operation.
//
// Get a list of all cars currently stored.
//
// GET /cars
func (UnimplementedHandler) ListCars(ctx context.Context) (r []Car, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateCarById implements updateCarById operation.
//
// Modify an existing car's details using its ID.
//
// PUT /cars/{id}
func (UnimplementedHandler) UpdateCarById(ctx context.Context, req *UpdateCar, params UpdateCarByIdParams) (r UpdateCarByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}
